services:
  pjud-scraper:
    build: .
    container_name: pjud-scraper
    ports:
      - "3000:3000"
    environment:
      # Configuración para Playwright en Docker
      - NODE_ENV=production
    # env_file:
    #   - .env
    restart: unless-stopped
    # Límites de recursos (ajustar segun necesidad)
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          memory: 512M
    # volumes:
    #   - ./data:/app/data
